site_name: Leetcode
site_description: leetcode solutions
site_author: Girish Thatte
site_url: https://girishgr8.github.io

nav:
    - Introduction: index.md
    - Standard Problems:
          - Dynamic Programming:
                - "0/1 Knapsack": dp/01knapsack.md
                - "Longest Common Subsequence(LCS)": dp/lcs.md
                - "Longest Palindromic Subsequence(LPS)": dp/lps.md
                - "Coin Change - minimum number of coins to make the change": dp/mincoinchange.md

    - Leetcode Problems:
          - "1. Two Sum": problems/1-two-sum.md
          - "2. Add Two Numbers": problems/2-add-two-numbers.md
          - "11. Container With Most Water": problems/11-container-with-most-water.md
          - "21. Merge Two Sorted Lists": problems/21-merge-two-sorted-lists.md
          - "34. Find First and Last Position of Element in Sorted Array": problems/34-find-first-and-last-position-of-element-in-sorted-array.md
          - "35. Search Insert Position": problems/35-search-insert-position.md
          - "40. Combination Sum II": problems/40-combination-sum-ii.md
          - "42. Trapping Rain Water": problems/42-trapping-rain-water.md
          - "46. Permutations": problems/46-permutations.md
          - "51. N-Queens": problems/51-n-queens.md
          - "56. Merge Intervals": problems/56-merge-intervals.md
          - "62. Unique Paths": problems/62-unique-paths.md
          - "63. Unique Paths II": problems/63-unique-paths-ii.md
          - "73. Set Matrix Zeroes": problems/73-set-matrix-zeroes.md
          - "74. Search a 2D Matrix": problems/74-search-a-2d-matrix.md
          - "75. Sort Colors": problems/75-sort-colors.md
          - "77. Combinations": problems/77-combinations.md
          - "89. Gray Code": problems/89-gray-code.md
          - "100. Same Tree": problems/100-same-tree.md
          - "153. Find Minimum in Rotated Sorted Array": problems/153-find-minimum-in-rotated-sorted-array.md
          - "200. Number of Islands": problems/200-number-of-islands.md
          - "203. Remove Linked List Elements": problems/203-remove-linked-list-elements.md
          - "206. Reverse Linked List": problems/206-reverse-linked-list.md
          - "216. Combination Sum III": problems/216-combination-sum-iii.md
          - "230. Kth Smallest Element in a BST": problems/230-kth-smallest-element-in-a-bst.md
          - "268. Missing Number": problems/268-missing-number.md
          - "322. Coin Change": problems/322-coin-change.md
          - "344. Reverse String": problems/344-reverse-string.md
          - "347. Top K Frequent Elements": problems/347-top-k-frequent-elements.md
          - "349. Intersection of Two Arrays": problems/349-intersection-of-two-arrays.md
          - "392. Is Subsequence": problems/392-is-subsequence.md
          - "516. Longest Palindromic Subsequence": problems/516-longest-palindromic-subsequence.md
          - "513. Find Bottom Left Tree Value": problems/513-find-bottom-left-tree-value.md
          - "537. Complex Number Multiplication": problems/537-complex-number-multiplication.md
          - "594. Longest Harmonious Subsequence": problems/594-longest-harmonious-subsequence.md
          - "609. Find Duplicate File in System": problems/609-find-duplicate-file-in-system.md
          - "682. Baseball Game": problems/682-baseball-game.md
          - "692. Top K Frequent Words": problems/692-top-k-frequent-words.md
          - "695. Max Area of Island": problems/695-max-area-of-island.md
          - "700. Search in a Binary Search Tree": problems/700-search-in-a-binary-search-tree.md
          - "785. Is Graph Bipartite?": problems/785-is-graph-bipartite.md
          - "797. All Paths From Source to Target": problems/797-all-paths-from-source-to-target.md
          - "876. Middle of the Linked List": problems/896-middle-of-the-linked-list.md
          - "897. Increasing Order Search Tree": problems/897-increasing-order-search-tree.md
          - "931. Minimum Falling Path Sum": problems/931-minimum-falling-path-sum.md
          - "967. Numbers With Same Consecutive Differences": problems/967-numbers-with-same-consecutive-differences.md
          - "1092. Shortest Common Supersequence": problems/1092-shortest-common-supersequence.md
          - "1143. Longest Common Subsequence": problems/1143-longest-common-subsequence.md
          - "1222. Queens That Can Attack the King": problems/1222-queens-that-can-attack-the-king.md
          - "1351. Count Negative Numbers in a Sorted Matrix": problems/1351-count-negative-numbers-in-a-sorted-matrix.md
          - "1539. Kth Missing Positive Number": problems/1539-kth-missing-positive-number.md
          - "1721. Swapping Nodes in a Linked List": problems/1721-swapping-nodes-in-a-linked-list.md
          - "1773. Count Items Matching a Rule": problems/1773-count-items-matching-a-rule.md
          - "1880. Check if Word Equals Summation of Two Words": problems/1880-check-if-word-equals-summation-of-two-words.md
          - "1980. Find Unique Binary String": problems/1980-find-unique-binary-string.md
          - "2053. Kth Distinct String in an Array": problems/2053-kth-distinct-string-in-an-array.md
          - "2085. Count Common Words With One Occurrence": problems/2085-count-common-words-with-one-occurrence.md
          - "2095. Delete the Middle Node of a Linked List": problems/2095-delete-the-middle-node-of-a-linked-list.md
          - "2130. Maximum Twin Sum of a Linked List": problems/2130-maximum-twin-sum-of-a-linked-list.md
          - "2224. Minimum Number of Operations to Convert Time": problems/2224-minimum-number-of-operations-to-convert-time.md

# https://squidfunk.github.io/mkdocs-material/

theme:
    highlightjs: true
    font:
        text: Roboto
    name: "material"
    language: en
    include_sidebar: true
    #favicon: assets/img/icon.png
    #logo: assets/img/logo.png
    icon:
        repo: fontawesome/brands/git-alt
    feature:
        tabs: false
    palette:
        primary: "indigo"
        accent: "deep orange"
    i18n:
        prev: "Previous"
        next: "Next"
    features:
        - navigation.sections
        - navigation.instant

copyright: "Copyright &copy; 2022 Girish Thatte"

extra_css:
    - stylesheets/extra.css
#     - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
    #     - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/
    #     - assets/js/extra.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - tags:
          tags_file: tags.md

# https://squidfunk.github.io/mkdocs-material/extensions/
markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
    - attr_list
    - admonition
    - footnotes
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.mark # highlight text
    - pymdownx.highlight:
          use_pygments: true # hljs is used instead of pygment for TOML highlighting support
          linenums: true
          linenums_style: pymdownx-inline
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - def_list
    - pymdownx.tilde
    - pymdownx.snippets:
          check_paths: true
    - toc:
          permalink: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
    disqus: "leetcode-solutions"
