site_name: Leetcode
site_description: leetcode solutions
site_author: Girish Thatte
site_url: https://girishgr8.github.io

nav:
    - Introduction: index.md
    - Problems:
          - "1. Two Sum": problems/1-two-sum.md
          - "2. Add Two Numbers": problems/2-add-two-numbers.md
          - "21. Merge Two Sorted Lists": problems/21-merge-two-sorted-lists.md
          - "34. Find First and Last Position of Element in Sorted Array": problems/34-find-first-and-last-position-of-element-in-sorted-array.md
          - "62. Unique Paths": problems/62-unique-paths.md
          - "73. Set Matrix Zeroes": problems/73-set-matrix-zeroes.md
          - "89. Gray Code": problems/89-gray-code.md
          - "153. Find Minimum in Rotated Sorted Array": problems/153-find-minimum-in-rotated-sorted-array.md
          - "203. Remove Linked List Elements": problems/203-remove-linked-list-elements.md
          - "206. Reverse Linked List": problems/206-reverse-linked-list.md
          - "268. Missing Number": problems/268-missing-number.md
          - "344. Reverse String": problems/344-reverse-string.md
          - "347. Top K Frequent Elements": problems/347-top-k-frequent-elements.md
          - "692. Top K Frequent Words": problems/692-top-k-frequent-words.md
          - "876. Middle of the Linked List": problems/896-middle-of-the-linked-list.md
          - "1351. Count Negative Numbers in a Sorted Matrix": problems/1351-count-negative-numbers-in-a-sorted-matrix.md
          - "1721. Swapping Nodes in a Linked List": problems/1721-swapping-nodes-in-a-linked-list.md
          - "1773. Count Items Matching a Rule": problems/1773-count-items-matching-a-rule.md
          - "2095. Delete the Middle Node of a Linked List": problems/2095-delete-the-middle-node-of-a-linked-list.md
          - "2130. Maximum Twin Sum of a Linked List": problems/2130-maximum-twin-sum-of-a-linked-list.md

# https://squidfunk.github.io/mkdocs-material/

theme:
    highlightjs: true
    font:
        text: Roboto
    name: "material"
    language: en
    include_sidebar: true
    #favicon: assets/img/icon.png
    #logo: assets/img/logo.png
    icon:
        repo: fontawesome/brands/git-alt
    feature:
        tabs: false
    palette:
        primary: "indigo"
        accent: "deep orange"
    i18n:
        prev: "Previous"
        next: "Next"
    features:
        - navigation.sections
        - navigation.instant

copyright: "Copyright &copy; 2022 Girish Thatte"

extra_css:
    - stylesheets/extra.css
#     - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
    #     - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/
    #     - assets/js/extra.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - tags:
          tags_file: tags.md

# https://squidfunk.github.io/mkdocs-material/extensions/
markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
    - attr_list
    - admonition
    - footnotes
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.mark # highlight text
    - pymdownx.highlight:
          use_pygments: true # hljs is used instead of pygment for TOML highlighting support
          linenums: true
          linenums_style: pymdownx-inline
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - def_list
    - pymdownx.tilde
    - pymdownx.snippets:
          check_paths: true
    - toc:
          permalink: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
    disqus: "leetcode-solutions"
